### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by nmanich**
Includes latest 2022 taxonomy
Retains WA example data
Has Dave's 2 fixed patches to fix whatever was up with compile_taxonomy section.

### CODE REVIEW

**Comment by nmanich** [comment]
@slager FYI this is sitting here whenever you get around to it. No rush but didn't want it to get entirely forgotten. :)

**Comment by slager** [comment]
The actual changes look good, but this has a lot of commits that undo and redo things.  Would it be okay if I squash them into one commit?  This would keep it cleaner in the repo, but its commit history would no longer match your local history.

**Comment by nmanich** [comment]
Certainly, please edit as you see fit

**Comment by slager** [comment]
Thanks for these! I merged it.  If doing another PR in the future, you'll just need to use this commit as a starting point to take care of the different commit histories issue.

**Pull request merged**
