### PR TITLE
Feature/na lightgray

### PR DESCRIPTION
**Pull request by ngwalton**
Bug fix (I think) to naming of regions in filter_data in crunch_filters. Added light gray color to NA filter limits.

### CODE REVIEW

**Review by slager — COMMENTED** [review]
Although it's a little confusing, setNames(regions) isn't a bug because it's assigning the name "regions" to an element within the nested list object, "filter_data". Because it's within another object, it doesn't conflict with the "regions" vector in the R namespace. A few lines above this, you can see that ordered_regions is being used as the basis for this list of regions.

If you can change this part back, I'll have a look at the NA-lightgray portion tomorrow morning and if it works I'll merge it in!

Thanks for the work and the close eye.

**Comment by ngwalton** [comment]
Actually, the reason I thought it was an error is that `ordered_regions` is used as the basis for this list of regions. If we name the results from `lapply(ordered_regions, ...)` using `regions` the names will be in the wrong order if the user has changed the order in `ordered_regions` from that of `regions`. If I understand how `setNames` is being used, the following seems analogous: 

```
regions <- letters[1:3]  # original regions
ordered_regions <- regions[3:1]  # user reorders regions

x <- lapply(ordered_regions, function(x) x)
names(x) <- regions
x
```

At the end, `x` has all the values of `ordered_regions`, but the names of `regions`. Isn't that what's happening in `filter_data`?

**Comment by ngwalton** [comment]
I followed this down stream and now see why it's not causing an issue. The portion of code in question is just making an empty data structure and `ordered_regions` is used to subset `filter_data` down stream. This is confusing, but I see why it isn't causing an issue as we expect `regions` and `ordered_regions` to contain the same values. Now I have to figure out how to fix my pull request :)

**Comment by slager** [comment]
Hey Nick, you're right.  I hadn't been thinking about it correctly -- perhaps it makes a lot more sense to have the filter_data structure use ordered_regions instead of regions.  Even though it doesn't actually change the result, it adds confusion to somebody reading the code, and could potentially cause problems if somebody bases a future analysis off the ordering within filter_data.  I'll try running your full patch this morning and if it works I'll keep the ordered_regions change in there!  (Neither of us see a reason why changing it to ordered_regions would be a problem, right?)

**Comment by ngwalton** [comment]
Yeah, I agree it will be less confusing and avoid potential issues down the road. I can't see any reason that changing it to ordered_regions would cause an issue.

**Review by slager — APPROVED** [review]
Worked great!

**Review by slager — APPROVED** [review]
All worked great

**Pull request merged**
